---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: centos8
    image: docker.io/geerlingguy/docker-centos8-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    pre_build_image: true
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
verifier:
  name: ansible
